version: '3'

services:
   app-db:
      image: mysql:latest
      environment:
         MYSQL_ROOT_PASSWORD: password
         MYSQL_DATABASE: app_db
      volumes:
         - app-data:/var/lib/mysql
      networks:
         - rschir-network

   app:
      build: app
      restart: always
      ports:
         - '8080:8080'
      environment:
         SPRING_DATASOURCE_URL: jdbc:mysql://app-db:3306/app_db
         SPRING_DATASOURCE_USERNAME: root
         SPRING_DATASOURCE_PASSWORD: password
         SERVER_PORT: 8080
      depends_on:
         - app-db
      networks:
         - rschir-network

   auth-db:
      image: mysql:latest
      command: mysqld --port=3307
      ports:
         - '3307:3307'
      environment:
         MYSQL_ROOT_PASSWORD: password
         MYSQL_DATABASE: auth_db
      volumes:
         - auth-data:/var/lib/mysql
      networks:
         - rschir-network

   # auth-db:
   #    image: redis
   #    ports:
   #       - '6379:6379'
   #    volumes:
   #       - auth-data:/data
   #    networks:
   #       - rschir-network

   auth-app:
      build: authentication
      restart: always
      ports:
         - '8081:8081'
      environment:
         # SPRING_REDIS_HOST: redis
         # SPRING_REDIS_PORT: 6379
         SPRING_DATASOURCE_URL: jdbc:mysql://auth-db:3307/auth_db
         SPRING_DATASOURCE_USERNAME: root
         SPRING_DATASOURCE_PASSWORD: password
         SERVER_PORT: 8081
      depends_on:
         # - redis
         - auth-db
      networks:
         - rschir-network


networks:
   rschir-network:

volumes:
   app-data:
   auth-data:
