version: '3'

services:

   nginx:
      image: nginx
      environment:
         - APP_PORT=$APP_PORT
      ports:
         - "90:90"
      volumes:
         - ./nginx.template.conf:/etc/nginx/templates/nginx.template.conf
      command: /bin/sh -c "envsubst < /etc/nginx/templates/nginx.template.conf > /etc/nginx/conf.d/default.conf
         && exec nginx -g 'daemon off;'"
      restart: always
      depends_on:
         - app
      networks:
         my-network:

   app:
      build:
         context: .
         dockerfile: app.Dockerfile
      ports:
         - "8080:8080"
      volumes:
         - ./gateway/logs.log:/app/gateway/logs.log
      networks:
         my-network:

   books:
      build:
         context: .
         dockerfile: books.Dockerfile
      depends_on:
         - books_mongo
      volumes:
         - ./services/booksAPI/logs.log:/app/services/booksAPI/logs.log
      networks:
         my-network:

   books_mongo:
      image: mongo
      ports:
         - "27017:27017"
      networks:
         my-network:

   tasks:
      build:
         context: .
         dockerfile: tasks.Dockerfile
      depends_on:
         - tasks_mongo
      volumes:
         - ./services/tasksAPI/logs.log:/app/services/tasksAPI/logs.log
      networks:
         my-network:

   tasks_mongo:
      image: mongo
      command: ["mongod", "--port", "27018"]
      ports:
         - "27018:27018"
      networks:
         my-network:

networks:
   my-network: